version: '3.9'
services:
  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    ports:
      - "9324:9324" # REST API
      - "9325:9325" # Web interface
    volumes:
      - ./src/main/resources/elasticmq.conf:/opt/elasticmq.conf
    command: -Dconfig.file=/opt/elasticmq.conf

  mongo:
    image: mongo:6.0
    container_name: matcher_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: participants